import Product from '#models/product'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await Product.createMany([
      {
        title: 'Croissant',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Pain au chocolat',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Pain au raisin',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Roulé praliné',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Croissant café',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Roulé canelle',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Chausson aux pommes',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Brioche nature',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Brioche choco',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Brioche tresse',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Babka',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Kouign aman',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
      {
        title: 'Brioche feuilletée',
        mardi: 0,
        mercredi: 0,
        jeudi: 0,
        vendredi: 0,
        samedi: 0,
        dimanche: 0,
        total: 0,
        paton: 0,
        unit: 0,
      },
    ])
  }
}
